config/routes.rb
Rails.application.routes.draw do


  root 'welcome#index'


  resources :appointments

  resources :patients, except: :index do
    resources :appointments, except: [:new, :create, :edit, :update]
  end


  get '/physicians/surgeons' => 'physicians#surgeons'


  resources :physicians do
    resources :appointments
  end





  get '/signin' => 'sessions#new'
  post '/sessions/create' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/physician.rb
class Physician < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  has_many :appointments
  has_many :patients, through: :appointments


  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true

  has_secure_password

  scope :type_of_Specialty, -> {where("specialty = ?", "Surgeon")}



end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :login_required, except: [:new, :show, :index, :create]
  before_action :find_physician, only: [:show, :edit, :update]

  def index
    @physicians = Physician.all
    respond_to do |format|
      format.html
      format.json {render json: @physicians}
    end
  end


  def show
    if @current_physician
      @appointments = Appointment.upcoming.where("physician_id = ?", @current_physician.id)
      respond_to do |format|
        format.html {render :show}
        format.json {render json: @physician}
      end
    else
      @appointments = nil
    end
  end


    def new
      if @current_physician
        flash[:notice] = "You are already a member of AppointmentMD"
        redirect_to physician_path(@current_physician)
      elsif @current_patient
        flash[:notice] = "You cannot create a Physician account"
        redirect_to patient_path(@current_patient)
      end
      @physician = Physician.new
    end


    def create
      @physician = Physician.new(physician_params)

      if @current_physician
        flash[:notice] = "You already have an account"
        redirect_to physician_path(@current_physician)
      elsif @current_patient
        flash[:notice] = "You can't create a Physician account"
        redirect_to patient_path(patient)
      end

      if @physician.save
        login_physician(@physician)
        flash[:notice] = "You have successfully created an account"
        redirect_to physician_path(@physician)
      else
        flash[:notice] = "There was an error creating a new Physician"
        render 'physicians/new'
      end
    end

    def edit
      if @current_physician
        unless @current_physician == @physician
          redirect_to physician_path(@current_physician)
        end
      elsif @current_patient
        redirect_to patient_path(@current_patient)
      else
        redirect_to root_path
      end
    end


    def update
      if @current_physician
        if @current_physician == @physician
          if @physician.update(physician_params)
            flash[:notice] = "Your info was successfully updated"
            redirect_to physician_path(@physician)
          else
            flash[:notice] = "Error updating Info! Plz make sure all fileds are filled out."
            render 'physicians/new'
          end
        else
          flash[:notice] = "You cannot edit another Physician's Info"
        end
      else
        flash[:notice] = "You have to be a Physician to edit a Physician's Info "
      end
    end

    def surgeons
      @physicians = Physician.type_of_Specialty
      render 'physicians/index'
    end



    private


    def physician_params
      params.require(:physician).permit(:name, :email, :uid, :specialty, :email, :password)
    end

    def find_physician
       @physician = Physician.find(params[:id])
    end


  end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/physicians/_form.html.erb
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <% if physician.errors[:name].any? %>
  <p><%= physician.errors.full_messages_for(:name)[0] %></p>
  <br>
  <% end %>

  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <% if physician.errors[:email].any? %>
  <p><%= physician.errors.full_messages_for(:email)[0]%></p>
  <br>
  <% end %>

  <%= f.label :specialty %>
  <%= f.text_field :specialty %>
  <br>
  <% if physician.errors[:specialty].any? %>
  <p><%= physician.errors.full_messages_for(:specialty)[0]%></p>
  <br>
  <% end %>

app/views/physicians/_view.html.erb
<div class='physician'>
<table>
  <tr>
    <th>Name</th>
    <td><%= physician.name %></td>
  </tr>
  <tr>
    <th>Specialty</th>
    <td><%= physician.specialty %></td>
  </tr>
  <% if current_page?(physician_path(physician)) %>
  <tr>
    <th>Email</th>
    <td><%= physician.email %></td>
  </tr>
  <% end %>
</table>
<button class="js-physician-data" data-id="<%=physician.id%>">Click to View more</button>
<div id="physician-appointments-html-area-<%= physician.id%>"></div><br></br>
</div>

app/views/physicians/edit.html.erb
<h1>Edit Physician Info</h1>
  <%= form_for @physician do |f| %>

  <%= render :partial => 'form', :locals => {:physician => @physician, :f =>  f} %>

  <%= f.submit "Update Physician Info" %>
  <% end %>


  <p><%= link_to "Back", physicians_path, class:"btn btn-primary btn-light" %></p>

app/views/physicians/index.html.erb
<h1>All Physician in AppointmentMD </h1>

<% @physicians.each do |physician| %>

 <%= render :partial => "view", :locals => {:physician => physician} %>



<% end %>
<%= link_to "View Only Surgeons", '/physicians/surgeons' %>

app/views/physicians/new.html.erb
<h1>Physician Sign Up Page</h1>

<%= form_for @physician do |f| %>

<%= render :partial => "form", :locals => { :physician => @physician, :f => f} %>

<%= f.label :password %>
<%= f.password_field :password %>
<br>
<% if @physician.errors[:password].any? %>
<p><%= @physician.errors.full_messages_for(:password)[0] %></p>
<br>
<% end %>

<%= f.submit "Signup" %>
<% end %>

<p><%= link_to('Sign Up with Facebook!', '/auth/facebook') %></p>
<h3>Click to go <%= link_to "Back", root_path, class:"btn btn-primary btn-light" %> to Welcome page</h3>

app/views/physicians/show.html.erb
<% if @physician == current_physician %>
<h1>Welcome to your HomePage</h1>
<% else %>
<h1>Physician View </h1>
<% end %>

<%= render :partial => "view", :locals => {:physician => @physician} %>



<% if @physician == current_physician %>
<p><button_tag><%= link_to "Edit Your Personal Info", edit_physician_path, class:"edit-physician-info"%></p>
<p><button_tag><%= link_to "View All Your Appointments", physician_appointments_path(@physician), class:"load-appointments"%></p>
<div id="appointments">
  <ol>
  </ol>
</div>
<p><button_tag><%= link_to "Create New Appointment", new_physician_appointment_path(@physician), class:"create-new-appointment-form"%></p>
<div id='new-appointment-form'>
</div>
<% end %>

<% if @physician == current_physician && !@appointments.nil? %>
<h2>Your Upcoming Appointments</h2>
<% @appointments.each do |a| %>
<%= render :partial => "appointments/view", :locals => {:a => a} %>
<% end %>

<% elsif @physician == current_physician %>
<h2>You have no upcoming appointments</h2>
<% end %>



<p><%= link_to "View All Physician", physicians_path, class:"all-physicians" %><p>