config/routes.rb
Rails.application.routes.draw do


  root 'welcome#index'


  resources :appointments

  resources :patients, except: :index do
    resources :appointments, except: [:new, :create, :edit, :update]
  end


  get '/physicians/surgeons' => 'physicians#surgeons'


  resources :physicians do
    resources :appointments
  end





  get '/signin' => 'sessions#new'
  post '/sessions/create' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h1> Welcome to AppointmentMD<h1>
  <%= image_tag ("/assets/rails_project_index.jpeg"), class: "img-responsive"%>
  <br></br>
  <br></br>



<h4>If You are a new Patient, please Sign Up by clicking the link below</h4>
<h3>
  <p>
    <%= link_to "Patient Sign Up", new_patient_path, class:"btn btn-primary btn-light" %>
  </p>
  <br>
</h3>

<h4>If You are a Physician, please Sign Up by clicking the link below</h4>
<h3>
  <p>
    <%= link_to "Physician Sign Up", new_physician_path, class:"btn btn-primary btn-light" %>
  </p>
  <br>
</h3>


<h4>Click to Login</h4>
<h3>
  <p>
    <%= link_to "Login", signin_path, class:"btn btn-primary btn-light" %>
  </p>
  <br>
</h3>