config/routes.rb
Rails.application.routes.draw do


  root 'welcome#index'


  resources :appointments

  resources :patients, except: :index do
    resources :appointments, except: [:new, :create, :edit, :update]
  end


  get '/physicians/surgeons' => 'physicians#surgeons'


  resources :physicians do
    resources :appointments
  end





  get '/signin' => 'sessions#new'
  post '/sessions/create' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  has_many :appointments
  has_many :physicians, through: :appointments

  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true

  has_secure_password
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
before_action :login_required, except: [:new, :create]
before_action :find_patient, except: [:new, :create]


  def show
  if @current_patient == @patient
    @appointment = @current_patient.appointments.upcoming
  else
    if @current_physician
      redirect_to physician_path(@current_physician)
     elsif @current_patient
      redirect_to patient_path(@current_patient)
     else
      redirect_to root_path
    end
   end
 end


  def new
    if @current_physician
      redirect_to physician_path(@current_physician)
    elsif @current_patient
      redirect_to patient_path(@current_patient)
    end
    @patient = Patient.new
  end


  def create
    @patient = Patient.new(patient_params)

    if @current_patient
      flash[:notice] = "You have an account in AppointmentMD"
      redirect_to patient_path(@current_patient)
    elsif @current_physician
      flash[:notice] = "A Physician cannot create a Patient account"
      redirect_to patient_path(@patient)
    end

    if @patient.save
      login_patient(@patient)
      flash[:notice] = "You have successfully created an account"
      redirect_to patient_path(@patient)
    else
      flash[:notice] = "There was an error "
      render "patients/new"
  end
end


def edit
  if @current_patient
    unless @current_patient == @patient
      redirect_to patient_path(@current_patient)
    end
  elsif @current_physician
    redirect_to physician_path(@current_physician)
  else
    redirect_to root_path
  end
end


  def update
    if @current_patient
      if @current_patient == @patient
        if @patient.update(patient_params)
          flash[:notice] = "Your info was successfully updated"
          redirect_to patient_path(@patient)
        else
          flash[:notice] = "Your info was not updated"
          render :new
        end
      else
        flash[:notice] = "You cannot edit another Patients info"
      end
    else
      flash[:notice] = "You cannot edit a Patients info"
    end
  end


  private


  def patient_params
    params.require(:patient).permit(:name, :email, :password, :age, :date_of_birth)
  end


  def find_patient
    @patient = Patient.find(params[:id])
  end


end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<% if patient.errors[:name].any? %>
<p><%= patient.errors.full_messages_for(:name)[0] %></p>
<br>
<% end %>

<%= f.label :email %>
<%= f.email_field :email %>
<br>
<% if patient.errors[:email].any? %>
<p><%= patient.errors.full_messages_for(:email)[0] %></p>
<br>
<% end %>

<%= f.label :age %>
<%= f.text_field :age %>
<br>
<% if patient.errors[:age].any? %>
<p><%= patient.errors.full_messages_for(:age)[0] %></p>
<br>
<% end %>

<%= f.label :date_of_birth %>
<%= f.date_field :date_of_birth %>
<br>
<% if patient.errors[:date_of_birth].any? %>
<p><%= patient.errors.full_messages_for(:date_of_birth)[0] %></p>
<br>
<% end %>

app/views/patients/edit.html.erb
<h1>Edit Patient Info</h1>

<%= form_for @patient do |f| %>

<%= render :partial => 'form', :locals => {:patient => @patient, :f => f} %>

<%= f.submit "Update Patient" %>
<% end %>

<%= link_to "Back", patient_path(@patient), class:"btn btn-primary btn-light" %>

app/views/patients/new.html.erb
<h1>Patient Sign Up Page</h1>

<%= form_for @patient do |f| %>

<%= render :partial => 'form', :locals => {:patient => @patient, :f => f} %>

<%= f.label :password %>
<%= f.password_field :password %>
<br>

<%= f.submit "Signup" %>
<% end %>

<h3>Click to go <%= link_to "Back", root_path, class:"btn btn-primary btn-light" %> to Welcome page</h3>

app/views/patients/show.html.erb
<h1>Patient Profile Page</h1>


<table>
  <tr>
    <th>Name</th>
    <td><%= @patient.name %></td>
  </tr>
  <tr>
    <th>Age</th>
    <td><%= @patient.age %></td>
  </tr>
  <tr>
    <th>Date of Birth</th>
    <td><%= @patient.date_of_birth %></td>
  </tr>
  <tr>
    <th>Email</th>
    <td><%= @patient.email %></td>
  </tr>
</table>


<% if @patient.appointments %>
<%= link_to "View appointments", patient_appointments_path(@patient) %>
<% end %>
<br>

<% if @patient == @current_patient %>
<%= link_to "Edit Your Info", edit_patient_path %>
<% end %>





<% if @patient == @current_patient && @patient.appointments.upcoming.any? %>

<h2>Appointments In The Next 2 Weeks</h2>

<% @patient.appointments.upcoming.each do |a| %>

<%= render :partial => "appointments/view", :locals => { :a => a} %>

<% end %>

<% elsif @patient == current_patient %>
<h2>You Have No Appointments Coming Up</h2>
<% end %>